import sys
import os
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import random
import math
import copy
from scipy.integrate import solve_ivp
from distance_functions import *
from mutation_functions import *
from dynamics import *
from utility_functions import *
from population_functions import *
from GRN_Expanded_Combinatorial import GRN
from Combine_Redundant_Attractors import *
import time
import sympy as sp

sys_path = os.getcwd()

# Get the input data from the command-line arguments
input_data = sys.argv[1]
Run_Num_input = int(float(input_data.split('|||')[1]))
input_data = input_data.split('|||')[0]
AM_input, f0_input, f0p_input, k_input, t1_input, t2_input, t3_input, c1_input, c2_input, c3_input, c4_input, TR_input, Deg_input, Lk_input, LG_input, Order_of_genes = json2ea(input_data)
########################################################################### Setting systematic Parameters #############################################################################
print('Message1\t'+'Input data received.')
TrainingCount = 3000
sys_PerturbationPower = 0.0
sys_random_seed = 42
TotalNumberOfGenes = int(np.sqrt(len(AM_input)))
#######################################################################################################################################################################################
StableStatesCollector = {}
def ParametersInitiations(null_net):
    '''Parameters Initiations'''
    # Name
    # mRNA
    Configuration = String012ToMatrix(AM_input)

    MutationRate = 0  # must be integer

    Sigmoid_k_init = eval(k_input)
    LogicGates = LogicGatesString2Matrix_Expanded(LG_input)
    f0_c = []
    TranscriptionThreshold = []
    for i in range(0, TotalNumberOfGenes):
        f0_c.append([])
        f0_c[-1].append(eval(f0_input)[i])
        f0_c[-1].append(eval(f0p_input)[i])
        f0_c[-1].append(eval(c1_input)[i])
        f0_c[-1].append(eval(c2_input)[i])
        f0_c[-1].append(eval(c3_input)[i])
        f0_c[-1].append(eval(c4_input)[i])
        TranscriptionThreshold.append([[100*eval(t1_input)[i], 100*eval(t2_input)[i], 100*eval(t3_input)[i]] for j in range(0, TotalNumberOfGenes)])

    DegradationRatemRNA = eval(Deg_input)
    Leakage =  eval(Lk_input)
    TranscriptionRate = eval(TR_input)

    return Configuration, MutationRate, TranscriptionRate, DegradationRatemRNA, TranscriptionThreshold, LogicGates, Sigmoid_k_init, Leakage, f0_c

########################################################################### Setting systematic Parameters #############################################################################
(Configuration, MutationRate, TranscriptionRate, DegradationRatemRNA, TranscriptionThreshold, LogicGates, Sigmoid_ks, Leakages, f0_c) = ParametersInitiations(False)
this_GRN = GRN('this_GRN', [], Configuration, MutationRate, TranscriptionRate, DegradationRatemRNA, TranscriptionThreshold, LogicGates, Sigmoid_ks, Leakages, f0_c)
indexes_of_diff_gene = [i for i, x in enumerate(DegradationRatemRNA) if x != 0]
Num_of_genes_diff_TPM = len(indexes_of_diff_gene)
TotalNumberOfGenes = len(this_GRN.f0_c)
print('Message2\t'+'Systematic parameters deployed.')
#######################################################################################################################################################################################
max_values = np.array([TranscriptionRate[i]/(DegradationRatemRNA[i]+1e-99) for i in range(0, TotalNumberOfGenes)])
min_values = np.array([Leakages[i]/(DegradationRatemRNA[i]+1e-99) for i in range(0, TotalNumberOfGenes)])
unique_counts = np.array([3 for i in range(0, TotalNumberOfGenes)])

if Run_Num_input == 1:
    combinations = [tuple(50 for howmany in range(0, TotalNumberOfGenes))]
else:
    total_iterations = Run_Num_input
    range_limits = [(min_values.tolist()[i], max_values.tolist()[i]) for i in range(0, TotalNumberOfGenes)]
    combinations = generate_limited_combinations(total_iterations, range_limits, unique_counts)

# Convert combinations to WTTPs:
WTTP = {}
KO_list = []
for combo_i in range(0, len(combinations)):
    WTTP[str(combo_i)] = [KO_list, np.array(combinations[combo_i])]
Overexpression = np.zeros((len(WTTP), TotalNumberOfGenes))
print('All\t'+str(len(WTTP)))
sys.stdout.flush()  # Ensure the output is flushed immediately

for Global_i in range(0, len(WTTP)):

    '''Setting up mRNA Protein numbers'''
    NewmRNA = np.array([0 for i in range(0, len(WTTP[str(Global_i)][1]))], dtype=float)

    for j in range(0, len(NewmRNA)):
        # The New mRNA list is generated by WTTP*Perturbation
        NewmRNA[j] = WTTP[str(Global_i)][1][j] * (1 + random.choice([1, -1]) * sys_PerturbationPower)

    #  Set overexpression or knockout
    this_GRN.SetmRNA(NewmRNA, WTTP[str(Global_i)][0], Overexpression[Global_i])

    # Run the model for a few times
    Start_time = time.time()
    mRNACheckList = []
    scipystring = this_GRN.Delta_mRNA_Network(WTTP[str(Global_i)][0], Overexpression[Global_i], indexes_of_diff_gene, this_GRN.mRNA)  # Calculate delta_mRNA
    #print(scipystring)

    exec(scipystring)
    #print('list(this_GRN.mRNA):', list(this_GRN.mRNA))
    sol = solve_ivp(update_mRNA_protein,
                    [0, TrainingCount],
                    list(this_GRN.mRNA),
                    args=([WTTP[str(Global_i)][0]]),
                    t_eval=[int(TrainingCount / 250) * tick for tick in range(0, 250 + 1)], method='RK45')

    npmRNA_continuous = sol.y[:TotalNumberOfGenes].T
    npmRNA = np.round(sol.y[:TotalNumberOfGenes]).T

    Plot_Curve = [[] for i in range(0, TotalNumberOfGenes)]
    Average_level = []
    End_time = time.time()
    for i in range(0, TotalNumberOfGenes):
        for j in range(0, npmRNA.shape[0]):
            Plot_Curve[i].append(npmRNA_continuous[j][i])

    for i in range(0, TotalNumberOfGenes):
        Average_level.append(np.mean(Plot_Curve[i][-50:]))

    #print('initial state:', list(np.round(this_GRN.mRNA[indexes_of_diff_gene],1)))
    #print('final state:  ', list(np.round(npmRNA_continuous[-1],1)[indexes_of_diff_gene]))

    '''Use the eigenvalues of Jacobian matrix to determine if this is a fixed-point attractor'''
    y = sp.symbols('y1:%d' % (Num_of_genes_diff_TPM + 1))
    point = {}
    for npmRNA_i in range(0, Num_of_genes_diff_TPM):
        point[y[npmRNA_i]] = npmRNA_continuous[-1][npmRNA_i]
    Jacobian_matrix = [[] for Jm_i in range(0, Num_of_genes_diff_TPM)]
    Derivative_values = []
    for eq_i in range(0, len(scipystring.split('\n'))):
        eq_string = scipystring.split('\n')[eq_i].replace(" ", "")
        if eq_string[:11] == 'delta_mRNA[':
            exec('eq_of_string = {}'.format(eq_string.split('=')[1]))
            Derivative_values.append(eq_of_string.subs(point))
            for var_j in range(0, len(y)):
                exec('df{}_dy{}_at_point = {}'.format(eq_i - 3, var_j, (sp.diff(eq_of_string, y[var_j])).subs(point)))
        else:
            continue
    for matrix_i in range(0, Num_of_genes_diff_TPM):
        for matrix_j in range(0, Num_of_genes_diff_TPM):
            Jacobian_matrix[matrix_i].append(eval('df{}_dy{}_at_point'.format(matrix_i, matrix_j)))
    eigenvalues = np.linalg.eigvals(Jacobian_matrix)
    Derivative_values = [abs(x) for x in Derivative_values]
    if max(eigenvalues) < 0 and max(Derivative_values) < (max(0.5, 0.01*np.max(npmRNA_continuous)) or eigenvalues+abs(Derivative_values[0])<0):
    #if max(eigenvalues) < 0 and max(Derivative_values) < max(0.5, 0.01*np.max(npmRNA_continuous)):
        IsPointAttractor = True
    else:
        IsPointAttractor = False
    #print('Eigenvalues: ', eigenvalues)
    #print('Derivative_values: ', Derivative_values)
    #print('IsPointAttractor: ', IsPointAttractor)
    #print('\n')
    ########################################################################################################################################################################################

    ############################################################################# Collect fixed-point attractor ############################################################################
    mRNA_list_for_compare = []
    for each in npmRNA_continuous[-1][indexes_of_diff_gene]:
        mRNA_list_for_compare.append(int(each))
        #print('mRNA_list_for_compare: ', mRNA_list_for_compare)

    if IsPointAttractor == True:
        #print(str(mRNA_list_for_compare))
        if str(mRNA_list_for_compare) in StableStatesCollector:
            StableStatesCollector[str(mRNA_list_for_compare)] = StableStatesCollector[str(mRNA_list_for_compare)] + 1
        else:
            StableStatesCollector[str(mRNA_list_for_compare)] = 1
    elif IsPointAttractor == False:
        pass
    else:
        raise Exception('Error!')
    print('Now\t'+str(Global_i))
    sys.stdout.flush()  # Ensure the output is flushed immediately

#print(StableStatesCollector)

if Run_Num_input == 1:
    print('***'+str((End_time-Start_time)*TotalNumberOfGenes)+'***')
    sys.stdout.flush()
else:
    pass

StableStates = []
Frequency_Threshold = 0
for keys in StableStatesCollector:
    if StableStatesCollector[keys] <= Frequency_Threshold:
        pass
    else:
        StableStates.append(eval(keys))

with open('./combinations_attractors.txt', 'a') as outfile:
    outfile.write(str(StableStates))

if len(StableStates) == 0:
    Combined = []
else:
    Combined = Combine_Redundant_Attractors(arrays = np.array(StableStates), cutoff=0.05)

Attractor_Distance_matrix = np.zeros((len(Combined), len(Combined)))
for novel_i in range(0, len(Combined)):
    for novel_j in range(0, len(Combined)):
        Attractor_Distance_matrix[novel_i][novel_j] = GetAttractorDistance(Combined[novel_i],Combined[novel_j],np.max(Combined, axis=0))
Unique_attractor_N = (1 + np.count_nonzero(np.mean(Attractor_Distance_matrix, axis=0) > 1))
Combined = np.round(Combined,1).tolist()
for i in range(0, len(Combined)):
    temp_list = [0]*TotalNumberOfGenes
    for j in range(0, TotalNumberOfGenes):
        if j in indexes_of_diff_gene:
            temp_list[j] = Combined[i][indexes_of_diff_gene.index(j)]
        else:
            pass
    Combined[i] = temp_list

print('Final|', Combined, '|', Order_of_genes)
sys.stdout.flush()  # Ensure the output is flushed immediately
